#!/bin/sh
set -eu

# Get functions and variables
for file in $(ls .setup); do
  . ".setup/$file"
done

# Verify packages
verify_packages requirements.txt

# Confirm override current user dotfiles
confirm "Accept overriding your current config files?"

# Git
link git/.gitconfig $HOME

# Neovim
link nvim $CONFIG

# Fish
link fish $CONFIG

# Alacritty
link alacritty $CONFIG

