require "plugins.packer"
require "plugins.autopairs"
require "plugins.bufferline"
require "plugins.comment"
require "plugins.lualine"
require "plugins.toggleterm"
require "plugins.tokyonight"
require "plugins.treesitter"
